// Generated by https://quicktype.io

export interface Account {
    page:          number;
    results:       Lista[];
    total_pages:   number;
    total_results: number;
}

export interface Lista {
    description:    string;
    favorite_count: number;
    id:             number;
    item_count:     number;
    iso_639_1:      string;
    list_type:      string;
    name:           string;
    poster_path:    null;
}


export interface FavoriteResponse {
    page:          number;
    results:       Fav[];
    total_pages:   number;
    total_results: number;
}

export interface Fav {
    original_language: string;
    original_title:    string;
    poster_path:       string;
    title:             string;
    video:             boolean;
    vote_average:      number;
    id:                number;
    release_date:      string;
    vote_count:        number;
    adult:             boolean;
    backdrop_path:     string;
    overview:          string;
    genre_ids:         number[];
    popularity:        number;
}



export class Favorite {
    media_type: string;
    media_id:   number;
    favorite: boolean;

    constructor(){
        this.media_type="movie";
        this.media_id=0;
        this.favorite=true;
    }
}
